reflexio/config/routes.rb
Reflexio::Application.routes.draw do

  resources :sites
  devise_for :users
  resources :users, :path => '/admin/users'

  get "home/index"

  root :to => 'sites#index'

end

reflexio/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, User
      can :manage, Site
    end
    can :manage, Site, :org => user.org
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

reflexio/app/models/site.rb
class Site
  include Mongoid::Document
  field :org, type: String, default: 'Public'
  field :url, type: String
  field :state, type: String, default: 'Pending'
  field :timestamp, type: DateTime
  field :status, type: String, default: 'In Progress'
  field :screenshot, type: String
  field :response_code, type: Integer, default: 0
  field :response_time, type: Float, default: 0

end

reflexio/app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  # Org definition used for segmentation
  field :org, :type => String, :default => 'Public'

  # Admin designator, grants access to all Orgs and User mgmt
  field :admin, :type => Boolean, :default => false

  # Approvable
  field :approved, :type => Boolean, :default => false
  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super
    end
  end

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

reflexio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :instantiateUser

  def instantiateUser
    @user = User.new
  end
  protect_from_forgery

end

reflexio/app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # This controller handles all site and report management.
  # All @sites and @site objects are loaded via cancan in the load_and_authorize method.
  
  # GET /sites
  # GET /sites.json
  before_filter :authenticate_user! 
  load_and_authorize_resource :site
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site.timestamp = Time.now()
    @site.org = current_user.org
    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    unless @site.nil?
      @site.state='Pending'
      @site.status = 'N/A'
      @site.timestamp = Time.now()
      @site.response_code = 0
      @site.response_time = 0
    end

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

end

reflexio/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  before_filter :authenticate_user! 
  load_and_authorize_resource 
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new()
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @user }
    end

  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    @user.approved =  params[:user][:approved] == '1'
    @user.admin =  params[:user][:admin] == '1'

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

reflexio/app/helpers/application_helper.rb
module ApplicationHelper
end

reflexio/app/helpers/home_helper.rb
module HomeHelper
end

reflexio/app/helpers/sites_helper.rb
module SitesHelper
end

reflexio/app/views/layouts/_navigation.html.erb
        <div class="inline_button_size primary_button">
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </div>
		<ul>
          <li><%= link_to current_user.email, edit_user_registration_path %>
          <% if (not current_user.nil?) && current_user.admin? %>
          <li><%= link_to 'Manage Users', users_path %></li>
		  <% end %>
		  <li><%= link_to 'New Site', new_site_path %></li>
          <li><%= link_to 'Site Listing', sites_path %></li>
        </ul>

reflexio/app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :url, :class => 'modal_input', :placeholder => 'URL' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'critical_button standard_button_size loginButton' %>
  </div>
<% end %>

reflexio/app/views/sites/edit.html.erb
<% content_for :page_title do %>Edit Site<% end %>
		  <% content_for :main_heading do %>
          <h1>Dashboard</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Editing <%= @site.url %></h3>
		  <% end %>
<%= render 'form' %>

<%= link_to 'Back', sites_path %>

reflexio/app/views/sites/index.html.erb
<h1>Manage Sites</h1>

<table class="banded">
  <tr>
    <th>Org</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @sites.each do |site| %>
    <% if cannot? :show, site 
        next
        end
      %>
  <tr>
    <td><%= site.org %></td>
    <td><%= site.url %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

reflexio/app/views/sites/show.html.erb
<% content_for :page_title do %>View Site Report<% end %>
		  <% content_for :main_heading do %>
          <h1>Site Report</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Details</h3>
            <%= link_to site_path(@site), :method => :put do %>
			<input name="button1" type="button" id="cmdNewTest" class="standard_button_size critical_button" value="Run New Test" style="float:right;" />
            <% end %>
		  <% end %>
<%= link_to 'Back', sites_path %> | 
<%= link_to 'Edit', edit_site_path(@site) %>

            <table class="prettygrid" cellspacing="0" cellpadding="0" rules="all" border="1" id="MainContent_gvResults" style="width:100%;border-collapse:collapse;">
              <tr class="prettygrid-header">
                <th align="center" scope="col">Parameter</th><th align="center" scope="col">Value</th>
              </tr>
              <tr class="prettygrid-row">
                <td align="left">Organization</td>
                <td align="left"><%= @site.org %></td>
			  </tr>
			  <tr class="prettygrid-alt">
                <td align="left">URL</td>
                <td align="left"><%= @site.url %></td>
              </tr>
              <tr class="prettygrid-row">
                <td align="left">Timestamp</td>
                <td align="left"><%= @site.timestamp %></td>
			  </tr>
			  <tr class="prettygrid-alt">
                <td align="left">Current State</td>
                <td align="left"><%= @site.state %></td>
              </tr>
			  <tr class="prettygrid-row">
                <td align="left">Response Time</td>
                <td align="left"><%= @site.response_time %> seconds</td>
			  </tr>
			  <tr class="prettygrid-alt">
                <td align="left">Status</td>
                <td align="left"><%= @site.status %></td>
              </tr>
			  <tr class="prettygrid-row">
                <td align="left">Response Code</td>
                <td align="left"><%= @site.response_code %></td>
              </tr>
			  <tr class="prettygrid-alt">
                <td align="left">Source IP (Whitelist This)</td>
                <td align="left"><%= t(:src_ip) %></td>
              </tr>
            </table>
			<br /><hr />
			<h3>Screenshot</h3>			
<% if @site.status == 'Success' %>
<%= image_tag('/screenshots/' + @site._id.to_s + '.png') %>
<% end %>

reflexio/app/views/sites/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url, :class => 'modal_input' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

reflexio/app/views/sites/sites/edit.html.erb
<% content_for :page_title do %>Edit Site<% end %>
		  <% content_for :main_heading do %>
          <h1>Dashboard</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Editing <%= @site.url %></h3>
		  <% end %>
<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

reflexio/app/views/sites/sites/index.html.erb
<% content_for :page_title do %>Manage Sites<% end %>
		  <% content_for :main_heading do %>
          <h1>Dashboard</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Manage Sites</h3>
		  <% end %>

            <table class="prettygrid" cellspacing="0" cellpadding="0" rules="all" border="1" id="MainContent_gvResults" style="width:100%;border-collapse:collapse;">
              <tr class="prettygrid-header">
                <th align="center" scope="col">Org</th><th align="center" scope="col">URL</th><th align="left" scope="col">Last Checked</th><th align="center" scope="col">Last Status</th><th align="center" scope="col">Status Report</th>
              </tr>
              <% @sites.each do |site| %>
              <tr class=<%= cycle("prettygrid-row", "prettygrid-alt") %>>
                <td align="center"><%= site.org %></td>
                <td align="left"><%= site.url %></td>
                <td align="left"><%= site.last_updated %></td>
                <td align="center">
                  <span class="rejected"><%= site.result %></span>
                </td>
                <td align="center" style="white-space:nowrap;">
                  <%= link_to 'Show', site %>
                  <%= link_to 'Edit', edit_site_path(site) %>
                  <%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
              <% end %>
            </table>

reflexio/app/views/sites/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

reflexio/app/views/sites/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @site.url %>
</p>
<p>
  <b>Last Attempt:</b>
  <%= @site.status %> 
</p>
<% if @site.status == 'Success' %>
<p>
  <b>Response Code:</b>
  <%= @site.response_code %>
</p>
<p>
  <b>Latency:</b>
  <%= @site.response_time %> seconds
</p>
<% end %>
<%= link_to 'Back', sites_path %> | 
<%= link_to 'Edit', edit_site_path(@site) %>

<% if @site.status == 'Success' %>
<%= image_tag('/screenshots/' + @site._id.to_s + '.png') %>
<% end %>

reflexio/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :email, :class => 'modal_input', :placeholder => 'EMail Address' %>
  </div>
  <div class="field">
    <%= f.text_field :org, :class => 'modal_input', :placeholder => 'Organization' %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'critical_button standard_button_size loginButton' %>
  </div>
<% end %>

reflexio/app/views/users/creates/edit.html.erb
<h1>Editing create</h1>

<%= render 'form' %>

<%= link_to 'Show', @create %> |
<%= link_to 'Back', creates_path %>

reflexio/app/views/users/creates/new.html.erb
<h1>New create</h1>

<%= render 'form' %>

<%= link_to 'Back', creates_path %>

reflexio/app/views/users/edit.html.erb
<% content_for :page_title do %>Edit User<% end %>
		  <% content_for :main_heading do %>
          <h1>Admin</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Editing <%= @user.email %></h3>
		  <% end %>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

reflexio/app/views/users/home/index.html.erb
<h1>Hello</h1>
<%= link_to "Site Listing", sites_path %>

reflexio/app/views/users/index.html.erb
<% content_for :page_title do %>Manage Users<% end %>
		  <% content_for :main_heading do %>
          <h1>Admin</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Manage Users</h3>
		  <% end %>

            <table class="prettygrid" cellspacing="0" cellpadding="0" rules="all" border="1" id="MainContent_gvResults" style="width:100%;border-collapse:collapse;">
              <tr class="prettygrid-header">
                <th align="center" scope="col">EMail</th><th align="center" scope="col">Organization</th><th align="left" scope="col">Approved</th><th align="center" scope="col">Admin</th><th align="center" scope="col">Manage</th>
              </tr>
              <% @users.each do |user| %>
              <tr class=<%= cycle("prettygrid-row", "prettygrid-alt") %>>
                <td align="center"><%= user.email %></td>
                <td align="left"><%= user.org %></td>
                <td align="center"><%= user.approved %></td>
                <td align="center"><% if user.admin? %><span class="rejected"><%= user.admin %></span><% else %><%= user.admin %><% end %></td>
                <td align="center" style="white-space:nowrap;">
                  <%= link_to 'Show', user %>
                  <%= link_to 'Edit', edit_user_path(user) %>
                  <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
              <% end %>
            </table>

reflexio/app/views/users/layouts/_navigation.html.erb
        <ul>
          <li><%= link_to 'Site Listing', sites_path %></li>
          <li><%= link_to 'New Site', new_site_path %></li>
          <% if (not current_user.nil?) && current_user.admin? %>
          <li><%= link_to 'Manage Users', users_path %></li>
          <% end %>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
        </ul>

reflexio/app/views/users/new.html.erb
<% content_for :page_title do %>New Users<% end %>
		  <% content_for :main_heading do %>
          <h1>Admin</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Create User</h3>
		  <% end %>
<%= render 'form' %>

<%= link_to 'Back', sites_path %>

reflexio/app/views/users/sites/edit.html.erb
<% content_for :page_title do %>Edit Site<% end %>
		  <% content_for :main_heading do %>
          <h1>Dashboard</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Editing <%= @site.url %></h3>
		  <% end %>
<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

reflexio/app/views/users/sites/index.html.erb
<% content_for :page_title do %>Manage Sites<% end %>
		  <% content_for :main_heading do %>
          <h1>Dashboard</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Manage Sites</h3>
		  <% end %>

            <table class="prettygrid" cellspacing="0" cellpadding="0" rules="all" border="1" id="MainContent_gvResults" style="width:100%;border-collapse:collapse;">
              <tr class="prettygrid-header">
                <th align="center" scope="col">Org</th><th align="center" scope="col">URL</th><th align="left" scope="col">Last Checked</th><th align="center" scope="col">Last Status</th><th align="center" scope="col">Status Report</th>
              </tr>
              <% @sites.each do |site| %>
              <tr class=<%= cycle("prettygrid-row", "prettygrid-alt") %>>
                <td align="center"><%= site.org %></td>
                <td align="left"><%= site.url %></td>
                <td align="left"><%= site.last_updated %></td>
                <td align="center">
                  <span class="rejected"><%= site.result %></span>
                </td>
                <td align="center" style="white-space:nowrap;">
                  <%= link_to 'Show', site %>
                  <%= link_to 'Edit', edit_site_path(site) %>
                  <%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
              <% end %>
            </table>

reflexio/app/views/users/sites/new.html.erb
<% content_for :page_title do %>New Site<% end %>
		  <% content_for :main_heading do %>
          <h1>Dashboard</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>New Site</h3>
		  <% end %>
<%= render 'form' %>

<%= link_to 'Back', sites_path %>

reflexio/app/views/users/sites/show.html.erb
<% content_for :page_title do %>View Site Report<% end %>
		  <% content_for :main_heading do %>
          <h1>Site Report</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Details</h3>
			<input name="button1" type="button" id="cmdNewTest" class="standard_button_size critical_button" value="Run New Test" style="float:right;" />
		  <% end %>
<%= link_to 'Back', sites_path %> | 
<%= link_to 'Edit', edit_site_path(@site) %>

            <table class="prettygrid" cellspacing="0" cellpadding="0" rules="all" border="1" id="MainContent_gvResults" style="width:100%;border-collapse:collapse;">
              <tr class="prettygrid-header">
                <th align="center" scope="col">Parameter</th><th align="center" scope="col">Value</th>
              </tr>
              <tr class="prettygrid-row">
                <td align="left">Organization</td>
                <td align="left"><%= @site.org %></td>
			  </tr>
			  <tr class="prettygrid-alt">
                <td align="left">URL</td>
                <td align="left"><%= @site.url %></td>
              </tr>
              <tr class="prettygrid-row">
                <td align="left">Last Updated</td>
                <td align="left"><%= @site.last_updated %></td>
			  </tr>
			  <tr class="prettygrid-alt">
                <td align="left">Current State</td>
                <td align="left"><%= @site.state %></td>
              </tr>
              <tr class="prettygrid-row">
                <td align="left">Timestamp</td>
                <td align="left"><%= @site.timestamp %></td>
			  </tr>
			  <tr class="prettygrid-alt">
                <td align="left">Status</td>
                <td align="left"><%= @site.status %></td>
              </tr>
              <tr class="prettygrid-row">
                <td align="left">Result</td>
                <td align="left"><%= @site.result %></td>
			  </tr>
			  <tr class="prettygrid-alt">
                <td align="left">Response Code</td>
                <td align="left"><%= @site.response_code %></td>
              </tr>
			  <tr class="prettygrid-row">
                <td align="left">Response Time</td>
                <td align="left"><%= @site.response_time %> seconds</td>
			  </tr>
            </table>
			<br /><hr />
			<h3>Screenshot</h3>			
<% if @site.status == 'Success' %>
<%= image_tag('/screenshots/' + @site._id.to_s + '.png') %>
<% end %>

reflexio/app/views/users/sites/sites/edit.html.erb
<% content_for :page_title do %>Edit Site<% end %>
		  <% content_for :main_heading do %>
          <h1>Dashboard</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Editing <%= @site.url %></h3>
		  <% end %>
<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

reflexio/app/views/users/sites/sites/index.html.erb
<% content_for :page_title do %>Manage Sites<% end %>
		  <% content_for :main_heading do %>
          <h1>Dashboard</h1>
		  <% end %>
		  <% content_for :sub_heading do %>
            <h3>Manage Sites</h3>
		  <% end %>

            <table class="prettygrid" cellspacing="0" cellpadding="0" rules="all" border="1" id="MainContent_gvResults" style="width:100%;border-collapse:collapse;">
              <tr class="prettygrid-header">
                <th align="center" scope="col">Org</th><th align="center" scope="col">URL</th><th align="left" scope="col">Last Checked</th><th align="center" scope="col">Last Status</th><th align="center" scope="col">Status Report</th>
              </tr>
              <% @sites.each do |site| %>
              <tr class=<%= cycle("prettygrid-row", "prettygrid-alt") %>>
                <td align="center"><%= site.org %></td>
                <td align="left"><%= site.url %></td>
                <td align="left"><%= site.last_updated %></td>
                <td align="center">
                  <span class="rejected"><%= site.result %></span>
                </td>
                <td align="center" style="white-space:nowrap;">
                  <%= link_to 'Show', site %>
                  <%= link_to 'Edit', edit_site_path(site) %>
                  <%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
              <% end %>
            </table>

reflexio/app/views/users/sites/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

reflexio/app/views/users/sites/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @site.url %>
</p>
<p>
  <b>Last Attempt:</b>
  <%= @site.status %> 
</p>
<% if @site.status == 'Success' %>
<p>
  <b>Response Code:</b>
  <%= @site.response_code %>
</p>
<p>
  <b>Latency:</b>
  <%= @site.response_time %> seconds
</p>
<% end %>
<%= link_to 'Back', sites_path %> | 
<%= link_to 'Edit', edit_site_path(@site) %>

<% if @site.status == 'Success' %>
<%= image_tag('/screenshots/' + @site._id.to_s + '.png') %>
<% end %>

reflexio/app/views/users/users/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

reflexio/app/views/users/users/index.html.erb
<h1>Manage User Approvals</h1>

<table class="banded">
  <tr>
    <th>Email</th>
    <th>Organization</th>
    <th>Approved</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.org %></td>
    <td><% if user.approved? %>
            Yes
        <% else %>
            No
        <% end %>  </td>
    <td><% if user.admin? %>
            Yes
        <% else %>
            No
        <% end %>  </td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>

  </tr>
<% end %>
</table>

<br />

reflexio/app/views/users/users/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

reflexio/app/views/users/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @user.email %>
</p>
<p>
  <b>Last Attempt:</b>
  <%= @user.org %> 
</p>
<%= link_to 'Back', users_path %> | 
<%= link_to 'Edit', edit_user_path(@user) %>